#!/usr/bin/env python3
"""Build data/verbs.js from the Notion Verbos snapshot kept by anki/notion_sync.py.

    python3 scripts/build_verbs.py                     # default cache path
    python3 scripts/build_verbs.py --cache path/to/notion_cache.json

Refresh the snapshot first with `python3 ../anki/notion_sync.py pull`.
Stdlib only. Writes a classic <script> (window.VERBS = [...]) rather than JSON
so the site also works when index.html is opened straight from disk.
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_CACHE = ROOT.parent / "anki" / "data" / "notion_cache.json"
OUT = ROOT / "data" / "verbs.js"

# Rows that are grammar patterns, not verbs you conjugate on their own.
SKIP_READINGS = {"〜てある", "〜ておく", "てくれる", "がる"}

# Notion rows whose Grupo is wrong. Keyed by reading; value is the correct group.
GROUP_FIXES = {
    "とじる": "2",      # 閉じる is ichidan
    "もっている": "2",  # ends in いる (ichidan)
    "いってくる": "3",  # compound of 来る
    # -eru/-iru ichidan verbs tagged Grupo 1
    "おちる": "2", "さげる": "2", "さめる": "2", "たずねる": "2", "てれびにでる": "2",
    "でかける": "2", "とれる": "2", "ながれる": "2", "みつける": "2",
    # godan verbs tagged Grupo 2
    "まいる": "1", "とりにかえる": "1",
}


def log(msg):
    print(msg, file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cache", type=Path, default=DEFAULT_CACHE)
    args = ap.parse_args()

    rows = json.loads(args.cache.read_text(encoding="utf-8"))["decks"]["Verbos"]["rows"]

    verbs, by_key = [], {}
    for row in rows:
        kana = (row.get("Hiragana") or "").strip()
        kanji = (row.get("Kanji") or "").strip() or kana
        # 〜て auxiliaries (てあげる, てみる…) are grammar, not verbs to drill.
        if not kana or kana in SKIP_READINGS or kana.startswith("〜") or kanji.startswith("て"):
            continue
        group = GROUP_FIXES.get(kana) or (row.get("Grupo") or "").replace("Grupo", "").strip()
        if group not in {"1", "2", "3"}:
            log(f"skip (no group): {kanji} {kana}")
            continue
        es = (row.get("Español") or "").strip()
        key = (kanji, kana)
        if key in by_key:
            # Same word, second sense (しまう: guardar / terminar): merge meanings.
            prev = by_key[key]
            if es and es not in prev["es"]:
                prev["es"] = f"{prev['es']} · {es}"
            continue
        verb = {
            "k": kanji,
            "r": kana,
            "g": group,
            "t": {"Transitivo": "tr", "Intransitivo": "intr"}.get(row.get("Tipo"), ""),
            "es": es,
            "ej": (row.get("Ejemplo") or "").strip(),
        }
        by_key[key] = verb
        verbs.append(verb)

    verbs.sort(key=lambda v: v["r"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_verbs.py from the Notion 'Verbos' database. Do not edit.\n"
        "window.VERBS = [\n"
        + ",\n".join(json.dumps(v, ensure_ascii=False) for v in verbs)
        + "\n];\n",
        encoding="utf-8",
    )
    log(f"wrote {len(verbs)} verbs -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
